language: node_js
node_js: 
  - lts/*
services:
  - docker
install:
  - npm ci
  - docker build -t dataservice:latest
  - docker images
script:
  - npm run coveralls
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

