apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dataservice
  name: dataservice
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: dataservice
  template:
    metadata:
      labels:
        app: dataservice
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: data-service-secrets
          image: gwdowner/dataservice:latest
          imagePullPolicy: Always
          name: dataservice
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
