apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dataservice-forecastcronjob
spec:
  schedule: "15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dataservice-forecast-job
            image: gwdowner/dataservice_job:latest
            command: ["npm",  "run", "batchjob:forecast"]
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: data-service-secrets
          restartPolicy: OnFailure
      backoffLimit: 5